apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-hrd5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-hrd5
    app.kubernetes.io/part-of: partner-catalog-1
  name: partner-catalog-hrd5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-hrd5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-hrd5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jbaxter1-tenant/partner-catalog-1/partner-catalog-hrd5@sha256:4fc690963c3e67979d023cf1e6218b8106f98368ea9e8210ecb35b4bff7fa6df
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
